[workspace]
members = [
	"apps/gateway",
	"common/*",
	"crates/*",
	"services/*"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
