[workspace]
members = [
	"crates/*",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
