[package]
name = "kosmos-render"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10"
bevy_terrain = { git = "https://github.com/kurtkuehnert/bevy_terrain", branch = "main" }
console_error_panic_hook = "0.1"
wasm-bindgen="0.2"
wee_alloc = "0.4"

[lib]
crate-type = ["cdylib"]
